### ISSUE TITLE
CD controller pod: hard requirement on control-plane label?

### ISSUE THREAD

**Issue by jgehrcke** [kubernetes-sigs/dra-driver-nvidia-gpu#308]
We seemingly currently error out (do not schedule the controller) if there is no node with a control-plane label. Do we want to keep that level of strictness, or do we want to apply more of a best-effort strategy? I don't know what the common practice really is in the k8s ecosystem. I have no opinion yet.

**Comment by bdw617** [comment]
It looks like this is here to just avoid scheduling on GPU nodes, which makes sense. If you don't have any non-GPU nodes, then you'll need to label one as this so the controller runs.

**Comment by jgehrcke** [comment]
> It looks like this is here to just avoid scheduling on GPU nodes, which makes sense.

I understand.

My question is if a less strict approach would also be viable. In that approach a control-plane label would be honored _if present_. However, if no such label is present we would not error out but still deploy all system components.

That could make a smoother out-of-the-box experience for certain use cases.

I also ask because my intuition is that this explicit human-in-the-loop will not change the outcome: when users do _not_ have nodes labeled as control-plane and when they then run into this error they typically quickly label a rather arbitrary node with that label (because if they had actual control plane nodes they would have labeled them). And we could have gotten there more quickly by just scheduling onto an arbitrary node.

I am still not of a strong opinion, but I wanted to make sure that the alternative I had in mind was understood.

**Comment by shivamerla** [comment]
We added the `nodeAffinity` to prefer control-plane nodes instead of strictly rejecting the pod [here](https://github.com/kubernetes-sigs/dra-driver-nvidia-gpu/blob/main/deployments/helm/dra-driver-nvidia-gpu/values.yaml#L256). Closing this.

```
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
```
